models:
  - name: shopify_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
        - from: inputs/rsOrderCompleted
  # Remove the section below, if you don't want to generate a feature table
  - name: shopify_user_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      features:
        - max_timestamp_tracks
        - max_timestamp_pages
        - max_timestamp_bw_tracks_pages
        - n_orders_completed
        - gross_amt_spent_in_past_90_days
        - days_since_last_seen
        - is_churned_7_days

var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: max_timestamp_tracks
          select: max(timestamp)
          from: inputs/rsTracks
          is_feature: false
      - entity_var:
          name: max_timestamp_pages
          select: max(timestamp)
          from: inputs/rsPages
          description: The total value of products that are part of the last transaction.
          is_feature: false
      - entity_var:
          name: max_timestamp_bw_tracks_pages
          select: CASE WHEN {{user.Var("max_timestamp_tracks")}}>={{user.Var("max_timestamp_pages")}} THEN {{user.Var("max_timestamp_tracks")}} ELSE {{user.Var("max_timestamp_pages")}} END
          is_feature: false
      # LTV features
      - entity_var:
          name: n_orders_completed
          default: 0
          select: count(*)
          from: inputs/rsOrderCompleted
          description: Total number of orders completed till date.
      - entity_var:
          name: gross_amt_spent_in_past_90_days
          default: 0
          select: sum(REVENUE)
          from: inputs/rsOrderCompleted
          where: "{{macro_datediff_n('timestamp','90')}}"
          description: Total amount spent in past 90 days.
      - entity_var:
          name: days_since_last_seen
          select: "{{macro_datediff('{{user.Var(\"max_timestamp_bw_tracks_pages\")}}')}}"
          default: 0
      - entity_var:
          name: is_churned_7_days
          select: case when {{user.Var("days_since_last_seen")}} > 7 then 1 else 0 end
          description: it specifies if there is any activity observed in the last n days. It is dependent on days_since_last_seen