models:
  - name: shopify_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
  # Remove the section below, if you don't want to generate a feature table
  - name: shopify_user_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      features:
        - days_since_last_seen
        - is_churned_7_days
        - days_since_account_creation
var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: max_timestamp
          select: max("timestamp")
          from: inputs/rsTracks
          is_feature: false
      - entity_var:
          name: days_since_last_seen
          select: "{{macro_datediff('{{user.Var(\"max_timestamp\")}}')}}"
          default: 0
      - entity_var:
          name: is_churned_7_days
          select: case when {{user.Var("days_since_last_seen")}} > 7 then 1 else 0 end
          description: it specifies if there is any activity observed in the last n days. It is dependent on days_since_last_seen
      - entity_var:
          name: days_since_account_creation
          select: "{{macro_datediff('min(\"timestamp\")')}}"
          from: inputs/rsIdentifies
