models:
  - name: shopify_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsTracks
        - from: inputs/rsPages
  - name: shopify_session_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: session
      edge_sources:
        - from: inputs/rsPages
  # Remove the section below, if you don't want to generate a feature table
  - name: shopify_user_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      features:
        - days_since_last_seen
        - is_churned_7_days
        - active_days_in_past_7_days
        - active_days_in_past_365_days
        - total_sessions_till_date
        - total_sessions_last_week
        - avg_session_length_in_sec_overall
        - avg_session_length_in_sec_last_week
        - avg_session_length_in_sec_365_days
        - first_seen_date
        - last_seen_date
        - total_sessions_90_days
        - total_sessions_365_days
        - has_seen_recently
        - last_seen_category
        - random_agg_event
  - name: shopify_session_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: session
      features:
        - session_end_time
        - session_start_time
        - session_length
        - user_id
        - anonymous_id
var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: max_timestamp_tracks
          select: max(timestamp)
          from: inputs/rsTracks
          is_feature: false
      - entity_var:
          name: max_timestamp_pages
          select: max(timestamp)
          from: inputs/rsPages
          description: The total value of products that are part of the last transaction.
          is_feature: false
      - entity_var:
          name: max_timestamp_bw_tracks_pages
          select: CASE WHEN {{user.Var("max_timestamp_tracks")}}>={{user.Var("max_timestamp_pages")}} THEN {{user.Var("max_timestamp_tracks")}} ELSE {{user.Var("max_timestamp_pages")}} END
          is_feature: false
      - entity_var:
          name: days_since_last_seen
          select: "{{macro_datediff('{{user.Var(\"max_timestamp_bw_tracks_pages\")}}')}}"
          default: 0
        # New boolean feature based on days_since_last_seen
      - entity_var:
          name: has_seen_recently
          select: CASE 
                    WHEN random() > 0.99 THEN null
                    WHEN {{user.Var("days_since_last_seen")}} <= 7 
                    THEN true
                    ELSE false END
          description: Whether the user has added a product to seen recently (within the last 7 days).
        # New categorical feature based on days_since_last_seen
      - entity_var:
          name: last_seen_category
          select: CASE
                  WHEN random() > 0.99 THEN null
                  WHEN {{user.Var("days_since_last_seen")}} <= 7 THEN 'recent'
                  WHEN {{user.Var("days_since_last_seen")}} <= 30 THEN 'moderate'
                  ELSE 'inactive' END  
          description: Categorical variable indicating seen activity.
      # New array type feature based on days_since_last_seen
      - entity_var:
          name: random_agg_event
          select: CASE WHEN random() > 0.99 THEN null ELSE array_agg(Distinct EVENT) END
          from: inputs/rsTracks
          description: Array type variable containing days since last seen 
      - entity_var:
          name: is_churned_7_days
          select: case when {{user.Var("days_since_last_seen")}} > 7 then 1 else 0 end
          description: it specifies if there is any activity observed in the last n days. It is dependent on days_since_last_seen    
      - entity_var:
          name: active_days_in_past_7_days
          select: count(distinct date(session_start_time))
          from: models/rsSessionTable
          where: "{{macro_datediff_n('session_start_time','7')}}"
          description: out of 7 days, how many days have recorded an event till date including today
      - entity_var:
          name: active_days_in_past_365_days
          select: count(distinct date(session_start_time))
          from: models/rsSessionTable
          where: "{{macro_datediff_n('session_start_time','365')}}"
          description: out of 365 days, how many days have recorded an event till date including todays date
      - entity_var:
          name: total_sessions_till_date
          from: models/rsSessionTable
          select: count(*)
          description: Total individual sessions created till date.
      - entity_var:
          name: total_sessions_last_week
          from: models/rsSessionTable
          select: count(*)
          where: "{{macro_datediff_n('session_start_time','7')}}"
          description: total number of sessions over last 7 days.
      - entity_var:
          name: total_sessions_90_days
          from: models/rsSessionTable
          select: count(*)
          where: "{{macro_datediff_n('session_start_time','90')}}"
          description: total number of sessions over last 90 days.
      - entity_var:
          name: total_sessions_365_days
          from: models/rsSessionTable
          select: count(*)
          where: "{{macro_datediff_n('session_start_time','365')}}"
          description: total number of sessions over last 365 days.
      - entity_var:
          name: avg_session_length_in_sec_overall
          from: models/rsSessionTable
          select: avg(session_length)
          description: Average session length (in seconds) of all the user sessions till date.
      - entity_var:
          name: avg_session_length_in_sec_last_week
          from: models/rsSessionTable
          select: avg(session_length)
          where: "{{macro_datediff_n('session_start_time','7')}}"
          description: Average session length (in seconds) of all the user sessions that started in last 7 days
      - entity_var:
          name: avg_session_length_in_sec_365_days
          from: models/rsSessionTable
          select: avg(session_length)
          where: "{{macro_datediff_n('session_start_time','365')}}"
          description: Average session length (in seconds) of all the user sessions that started in last 365 days
      - entity_var:
          name: first_seen_date
          from: models/rsSessionTable
          select: min(date(session_start_time))
          description: The first date on which an event has been recorded by the user
      - entity_var:
          name: last_seen_date
          from: models/rsSessionTable
          select: max(date(session_end_time))
          description: The latest date on which an event has been recorded by the user
  - name: session_vars
    entity_key: session
    vars:
      - entity_var:
          name: session_end_time
          select: max(timestamp)
          from: inputs/rsPages
      - entity_var:
          name: session_start_time
          select: min(timestamp)
          from: inputs/rsPages
      - entity_var:
          name: session_length
          select: TIMESTAMPDIFF(SECOND, {{session.Var("session_start_time")}}, {{session.Var("session_end_time")}})
      - entity_var:
          name: user_id
          select: last_value(user_id)
          where: user_id is not null
          window:
            order_by:
              - timestamp
          from: inputs/rsPages
      - entity_var:
          name: anonymous_id
          select: last_value(anonymous_id)
          where: anonymous_id is not null
          window:
            order_by:
              - timestamp
          from: inputs/rsPages
